"""Add investments and investment_metrics tables

Revision ID: 702d7f7b6efb
Revises: b64f6b3c4288
Create Date: 2025-11-01 12:38:08.536400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702d7f7b6efb'
down_revision: Union[str, None] = 'b64f6b3c4288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'investment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('total_investment_value', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('installments', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('installment_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('installment_months', sa.Integer(), nullable=True),
        sa.Column('gain_in_income_percent', sa.Numeric(precision=6, scale=3), nullable=False, server_default='0.000'),
        sa.Column('cadence', sa.String(), nullable=False, server_default='monthly'),
        sa.Column('one_off_inflow_value', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'),
        sa.Column('salvage_value', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'),
        sa.Column('discount_rate_annual_percent', sa.Numeric(precision=6, scale=3), nullable=False, server_default='15.000'),
        sa.Column('reinvestment_rate_annual_percent', sa.Numeric(precision=6, scale=3), nullable=False, server_default='15.000'),
        sa.Column('analysis_horizon_months', sa.Integer(), nullable=False, server_default='60'),
        sa.Column('break_even_fixed_costs', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'),
        sa.Column('break_even_price_per_unit', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'),
        sa.Column('break_even_variable_cost_per_unit', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_investment_user_id', 'investment', ['user_id'])
    op.create_index('idx_investment_name', 'investment', ['name'])
    
    op.create_table(
        'investment_metric',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('investment_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('roi_percent', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('npv', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('irr_percent', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('mirr_percent', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('payback_months', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('discounted_payback_months', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('profitability_index', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('cagr_percent', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('break_even_units', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_investment_metric_investment_id', 'investment_metric', ['investment_id'])
    op.create_index('idx_investment_metric_user_id', 'investment_metric', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_investment_metric_user_id', 'investment_metric')
    op.drop_index('idx_investment_metric_investment_id', 'investment_metric')
    op.drop_table('investment_metric')
    
    op.drop_index('idx_investment_name', 'investment')
    op.drop_index('idx_investment_user_id', 'investment')
    op.drop_table('investment')
    # ### end Alembic commands ###
