"""Create initial tables

Revision ID: b64f6b3c4288
Revises: 
Create Date: 2025-11-01 11:03:17.248377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b64f6b3c4288'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_slug', 'assets', ['user_id', 'slug'], unique=True)
    op.create_index(op.f('ix_assets_slug'), 'assets', ['slug'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('month_networth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('networth', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_month_networth', 'month_networth', ['user_id', 'year_month'], unique=True)
    op.create_index(op.f('ix_month_networth_user_id'), 'month_networth', ['user_id'], unique=False)
    op.create_table('asset_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_asset_month', 'asset_valuations', ['user_id', 'asset_id', 'year_month'], unique=True)
    op.create_index('idx_user_month', 'asset_valuations', ['user_id', 'year_month'], unique=False)
    op.create_index(op.f('ix_asset_valuations_user_id'), 'asset_valuations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_valuations_user_id'), table_name='asset_valuations')
    op.drop_index('idx_user_month', table_name='asset_valuations')
    op.drop_index('idx_user_asset_month', table_name='asset_valuations')
    op.drop_table('asset_valuations')
    op.drop_index(op.f('ix_month_networth_user_id'), table_name='month_networth')
    op.drop_index('idx_user_month_networth', table_name='month_networth')
    op.drop_table('month_networth')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_slug'), table_name='assets')
    op.drop_index('idx_user_slug', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
